[milesmcc]
name = "Miles McCain"
website = "https://miles.land"
github = "milesmcc"
email = "privacyspy@sendmiles.email"
role = "founder"

[ibarakaiev]
name = "Igor Barakaiev"
website = "https://igor.fyi"
github = "ibarakaiev"
email = "privacyspy@igor.fyi"
role = "founder"

[doamatto]
name = "Matt"
website = "https://doamatto.xyz"
github = "doamatto"
email = "hello@doamatto.xyz"

[UnKnOwN]

[YuriiStasiuk]

[kulchynska]

[owlswipe]

[ftsell]

[nep]

[yaagesoft]

[RambosRide]

[unbeatable101]

[Anastasia]

[vutut]

[mrhedgehog0]

[Wingo5315]
