name = "BBC"
description = "The British Broadcasting Corporation is a British public service broadcaster."
slug = "bbc"
hostnames = ["bbc.co.uk", "bbc.com"]
sources = ["https://www.bbc.co.uk/usingthebbc/privacy-policy"]
contributors = ["Wingo5315"]

[rubric.behavioral-marketing]
value = "yes-opt-in"
citations = ["We\'ll only send you marketing emails or contact you about BBC programmes, services and your views on issues about the BBC if you\'ve agreed to this."]

[rubric.data-breaches]
value = "no"
citations = [""]

[rubric.data-collection-reasoning]
value = "mostly"
citations = ["We have to have a valid reason to use your personal information. It's called the \'lawful basis for processing\'. Sometimes we might ask your permission to do things, like when you subscribe to an email. Other times, when you\'d reasonably expect us to use your personal information, we don't ask your permission, but only when the law says it\'s fine to use it, and it fits with the rights you have."]
notes = ["The full list of why the BBC collects personal information is in Section 6 of the Privacy Policy."]

[rubric.data-deletion]
value = "yes-automated"
citations = ["This depends on what information you're talking about. You can delete your account. Your account information is immediately deleted. Keep in mind we keep a record of how you've used our services, but this information can't be linked back to you (and) we also keep anything you\'ve uploaded or commented on. We might have collected other personal information that you might ask to be deleted that has nothing to do with BBC account."]

[rubric.history]
value = "last-modified"
citations = [""]

[rubric.law-enforcement]
value = "not-specified"
citations = ["Sometimes by law we have to pass on your information to other organisations. We might also share your information if we have to by law, or when we need to protect you or other people from harm."]

[rubric.list-collected]
value = "generally"
citations = ["We\'ll give you details about why we need your personal information and how we'll use it before you begin, unless it\'s obvious.
a. Information that you give us
We might ask for your name and contact details, your date of birth or financial details, depending on what you're doing. If you apply to take part in a programme on politics, for example, we might ask you about your political opinions. Information you give us might include information in a creation you share with us, such as people's names that appear in the creation.
When you register for a BBC account, or update your details or settings we ask for some personal information, like your email address and age.
b. Device information
Devices are lots of things like your computer, your mobile, your TV, your tablet and your voice-enabled device.
We automatically collect some technical information from these devices and web browsers even when you\'re not signed into to a BBC account. This might include IP (internet protocol) address, device ID, app ID, vendor ID, advertising ID
c. Information on your activities outside the BBC when you talk about us
Like if you've mentioned us in a Twitter post, we\'ll collect your Twitter handle.
d. Information on how you use our services
Like the articles you read and the programmes you watch."]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [""]

[rubric.revision-notify]
value = "yes"
citations = ["We update this policy sometimes. If we make important changes, like how we use your personal information, we\'ll let you know. It might be a notice, an email or a message in your app."]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = ["We\'ll never sell your personal information. We do share it with others in these ways:
a. When you make something public
Like post a comment which the public can see.
b. When we use other companies to power our services
In order for us to give you quality experiences and to understand how you're using our services we often use other companies to process your personal information on our behalf. For example, sending you emails about things we think might interest you, to ask you what you think about our services, or to analyse data on how people use our digital services so we can improve them.
We make sure that your personal information is looked after as if we were handling it directly. We carefully select these companies, only share with them what they need to do the work and we make sure they keep your information secure.
c. When we share personal information with companies in the BBC family
d. When you use another company's service that connects to us, like voice-enabled devices and connected TV
You can access our services through a voice-enabled device, like Amazon Alexa, or a connected TV. You’ll need to sign in to your BBC account to use BBC services on your connected TV. When you do this we’ll share an identifier for your BBC account with the company who runs the service you are using. Make sure to check that company\'s privacy policy so you know how it will use your information. The BBC isn\'t responsible when you access a BBC service through another company’s services. It\'s up to you if you want to access the BBC in this way.
e. When we do collaborative research
We do research activities and sometimes collaborate with research partners. Every now and then we share our content and data with them. This might include information we\'ve collected about you. But we\'re careful about what we share and what our research partners can do with it.
f. TV Licensing
We share some personal information with TV Licensing, to check if you\'re using BBC iPlayer and to keep the licensing database accurate and up to date.
g. Sometimes by law we have to pass on your information to other organisations
We might also share your information if we have to by law, or when we need to protect you or other people from harm."]

[rubric.third-party-collection]
value = "yes"
citations = [""]
