name = "protonMail"
description = "ProtonMail is an end-to-end encrypted email service founded in 2013 in Geneva, Switzerland by scientists who spent time at the CERN research facility."
slug = "protonmail"
hostnames = [ "protonmail.com"]
sources = [ "https://protonmail.com/privacy-policy" ]
contributors = [ "erotavlas" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  ""
]

[rubric.security]
value = "somewhat"
citations = [
  ""
]

[rubric.third-party-collection]
value = "critical-only"
citations = [
  ""]

[rubric.history]
value = "yes"
notes = [
    ""
]

[rubric.data-deletion]
value = "no"
citations = [
  ""
]
  
[rubric.data-breaches]
value = "no"
notes = [
   ""]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = [
  ".."
]

[rubric.data-collection-reasoning]
value = "mostly"
notes = [
  ""
]

[rubric.noncritical-purposes]
value = "na"
citations = [
  ".."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "" 
]
    
[rubric.list-collected]
value = "exhaustively"
citations = [
  ""
]

[rubric.revision-notify]
value = "yes"
citations = [
    ""
]

