name = "protonVPN"
description = "ProtonVPN is a VPN service provider operated by the Swiss company Proton Technologies AG, the company behind the email service ProtonMail."
slug = "protonvpn"
hostnames = [ "protonvpn.com"]
sources = [ "https://protonvpn.com/privacy-policy" ]
contributors = [ "erotavlas" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  ""
]

[rubric.security]
value = "somewhat"
citations = [
  ""
]

[rubric.third-party-collection]
value = "critical-only"
citations = [
  ""]

[rubric.history]
value = "yes"
notes = [
    ""
]

[rubric.data-deletion]
value = "no"
citations = [
  ""
]
  
[rubric.data-breaches]
value = "no"
notes = [
   ""]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = [
  ".."
]

[rubric.data-collection-reasoning]
value = "mostly"
notes = [
  ""
]

[rubric.noncritical-purposes]
value = "na"
citations = [
  ".."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "" 
]
    
[rubric.list-collected]
value = "exhaustively"
citations = [
  ""
]

[rubric.revision-notify]
value = "yes"
citations = [
    ""
]

