name = "Signal"
description = "Signal is a cross-platform encrypted messaging service."
slug = "signal"
hostnames = [ "signal.org"]
sources = [ "https://signal.org/legal/#privacy-policy" ]
contributors = [ "erotavlas" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "\"Signal does not sell, rent or monetize your personal data or content in any way – ever.\""
]

[rubric.security]
value = "yes"
citations = [
  "\"Signal utilizes state-of-the-art security and end-to-end encryption to provide private messaging and Internet calling services to users worldwide (\"Services\"). Your calls and messages are always encrypted, so they can never be shared or viewed by anyone but yourself and the intended recipients.\""
]

[rubric.third-party-collection]
value = "no"
notes = ["Signal does not collect any data from third parties."]

[rubric.history]
value = "last-modified"
notes = [ "\"We will update this privacy policy as needed so that it is current, accurate, and as clear as possible. Your continued use of our Services confirms your acceptance of our updated Privacy Policy.\""]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"If you contact Signal User Support, any personal data you may share with us is kept only for the purposes of researching the issue and contacting you about your case. Additional technical information is stored on our servers, including randomly generated authentication tokens, keys, push tokens, and other material that is necessary to establish calls and transmit messages. Signal limits this additional technical information to the minimum required to operate the Services.\""]
  
notes = [
  "\"You register a phone number when you create a Signal account. Phone numbers are used to provide our Services to you and other Signal users. You may optionally add other information to your account, such as a profile name and profile picture. This information is end-to-end encrypted.\" \r\n\r\n \"Signal can optionally discover which contacts in your address book are Signal users, using a service designed to protect the privacy of your contacts. Information from the contacts on your device may be cryptographically hashed and transmitted to the server in order to [determine which of your contacts are registered](https://signal.org/blog/contact-discovery/).\""
]

[rubric.data-breaches]
value = "na"
notes = [
    "The service collects so little personal data that notification would not be possible."]

[rubric.third-party-access]
value = "no"
citations = [
  "\"We work with third parties to provide some of our Services. For example, our Third-Party Providers send a verification code to your phone number when you register for our Services. These providers are bound by their Privacy Policies to safeguard that information. If you use other Third-Party Services like YouTube, Spotify, Giphy, etc. in connection with our Services, their Terms and Privacy Policies govern your use of those services.\" \r\n\r\n \"Other instances where Signal may need to share your data: To meet any applicable law, regulation, legal process or enforceable governmental request. To enforce applicable Terms, including investigation of potential violations. To detect, prevent, or otherwise address fraud, security, or technical issues. To protect against harm to the rights, property, or safety of Signal, our users, or the public as required or permitted by law.\""
]

[rubric.data-collection-reasoning]
value = "na"
citations = [
  "\"Signal is designed to never collect or store any sensitive information. Signal messages and calls cannot be accessed by us or other third parties because they are always end-to-end encrypted, private, and secure.\""
]

[rubric.noncritical-purposes]
value = "na"
citations = [
  "\"Signal is designed to never collect or store any sensitive information. Signal messages and calls cannot be accessed by us or other third parties because they are always end-to-end encrypted, private, and secure.\""
]

[rubric.law-enforcement]
value = "na"
citations = [
  "\"Signal is designed to never collect or store any sensitive information. Signal messages and calls cannot be accessed by us or other third parties because they are always end-to-end encrypted, private, and secure.\" \r\n\r\n \"Other instances where Signal may need to share your data: To meet any applicable law, regulation, legal process or enforceable governmental request. To enforce applicable Terms, including investigation of potential violations. To detect, prevent, or otherwise address fraud, security, or technical issues. To protect against harm to the rights, property, or safety of Signal, our users, or the public as required or permitted by law. [Subpoena](https://signal.org/bigbrother/eastern-virginia-grand-jury/).\""
]

[rubric.list-collected]
value = "na"
citations = [
  "\"Signal is designed to never collect or store any sensitive information. Signal messages and calls cannot be accessed by us or other third parties because they are always end-to-end encrypted, private, and secure.\""
]
  
notes = [
  "\"If you contact Signal User Support, any personal data you may share with us is kept only for the purposes of researching the issue and contacting you about your case. Additional technical information is stored on our servers, including randomly generated authentication tokens, keys, push tokens, and other material that is necessary to establish calls and transmit messages. Signal limits this additional technical information to the minimum required to operate the Services.\""]

[rubric.revision-notify]
value = "na"
citations = [
  "\"Signal is designed to never collect or store any sensitive information. We will update this privacy policy as needed so that it is current, accurate, and as clear as possible. Your continued use of our Services confirms your acceptance of our updated Privacy Policy.\""
]
