name = "Telegram"
description = "Telegram is a messaging app with a focus on speed and security, it’s super-fast, simple and free."
slug = "telegram"
hostnames = [ "telegram.org"]
sources = [ "https://telegram.org/privacy" ]
contributors = [ "erotavlas" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "Unlike other services, we don't use your data for ad targeting or other commercial purposes. Telegram only stores the information it needs to function as a secure and feature-rich cloud service."]

[rubric.security]
value = "yes"
citations = [
  "We will process your data to deliver your cloud chat history, including messages, media and files, to any devices of your choosing without a need for you to use third-party backups or cloud storage. All data is stored heavily encrypted so that local Telegram engineers or physical intruders cannot get access. We employ all appropriate technical and organizational measures (including encryption of your personal data) to ensure a level of security for your personal data that is appropriate to the risk. \r\n\r\n Unless stated otherwise in this Privacy Policy, the personal data that you provide us will only be stored for as long as it is necessary for us to fulfill our obligations in respect of the provision of the Services. \r\n\r\n Your messages, media and files from [secret chats](https://telegram.org/privacy#3-3-2-secret-chats), as well as the contents of your calls and the data you store in your [Telegram Passport](https://telegram.org/blog/passport) are processed only on your device and on the device of your recipient. While Telegram servers will handle this end-to-end encrypted data to deliver it to the recipient – or store it in the case of Telegram Passport data, we have no ways of deciphering the actual information."]

[rubric.third-party-collection]
value = "no"
citations = ["Telegram does not collect any data from third parties."]

[rubric.history]
value = "yes"
notes = [ "Please check our website frequently to see any updates or changes to our [Privacy Policy](https://telegram.org/privacy#11-changes-to-this-privacy-policy), a summary of which we will set out below."]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "If you would like to delete your account, you can do this on the deactivation page. Deleting your account removes all messages, media, contacts and every other piece of data you store in the Telegram cloud. This action must be confirmed via your Telegram account and cannot be undone."]
  
notes = [
  "By default, if you stop using Telegram and do not come online for at least 6 months, your account will be deleted along with all messages, media, contacts and every other piece of data you store in the Telegram cloud. You can go to Settings to change the exact period after which your inactive account will self-destruct. [Account Self-Destruction](https://telegram.org/privacy#10-4-account-self-destruction)."]

[rubric.data-breaches]
value = "no"
notes = [ "The policy does not specify a data breach protocol."]

[rubric.third-party-access]
value = "yes-specified-critical"
citations = [
  "We may share your personal data with: (1) our parent company, Telegram Group Inc, located in the British Virgin Islands; and (2) Telegram FZ-LLC, a group member located in Dubai, to help provide, improve and support our Services. We will implement appropriate safeguards to protect the security and integrity of that personal data. This will take the form of standard contract clauses approved by the European Commission in an agreement between us and our relevant group companies. If you would like more information regarding these clauses, please contact us [Questions and concerns](https://telegram.org/privacy#12-questions-and-concerns). \r\n\r\n Telegram has an API that allows third-party developers to create [bots](https://telegram.org/privacy#6-bot-messages). Bots are apps that look like special Telegram users: you can talk to them from your chat list, add them to groups or use a special \"inline\" interface to access their features. By performing any of these actions, you will be sending some of your data to the respective third-party bot developers. Other than our own bots, no other bots or third-party bot developers are affiliated with Telegram. They are completely independent from us. They should ask you for your permission before they access your data or you make it available to them. \r\n\r\n Telegram does not process payments from users and instead relies on different payment providers around the world. Neither Telegram nor the merchants on the platform (bot developers) have access to this information. Although we work with payment providers they are completely independent from Telegram. Your credit card information never reaches Telegram's servers. [Third Party Payment Services](https://telegram.org/privacy#7-third-party-payment-services)."]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "Telegram has two fundamental principles when it comes to collecting and processing private data: We don't use your data to show you ads. We only store the data that Telegram needs to function as a secure and feature-rich messaging service."]

[rubric.noncritical-purposes]
value = "na"
citations = [
  "No Ads. Unlike other services, we don't use your data for ad targeting or other commercial purposes. Telegram only stores the information it needs to function as a secure and feature-rich cloud service."]

[rubric.law-enforcement]
value = "strict"
citations = [
  "If Telegram receives a court order that confirms you're a terror suspect, we may disclose your IP address and phone number to the relevant authorities. So far, this has never happened. When it does, we will include it in a semiannual [transparency report](https://t.me/transparency)."]

[rubric.list-collected]
value = "exhaustively"
citations = [
  "You provide your mobile number and basic account data (which may include profile name, profile picture and about information) to create a Telegram account. Telegram uses phone numbers as unique identifiers so that it is easy for you to switch from SMS and other messaging apps and retain your social graph. We ask your permission before syncing your contacts. You can always stop syncing contacts or delete them from our servers in Settings > Privacy & Security > Data Settings. \r\n\r\n When you enable 2-step-verification for your account or store documents using the [Telegram Passport](https://telegram.org/blog/passport) feature, you can opt to set up a password recovery email. This address will only be used to send you a password recovery code if you forget it. That's right: no marketing or \"we miss you\" bullshit.\r\n\r\n We store messages, photos, videos and documents from your cloud chats on our servers so that you can access your data from any of your devices anytime without having to rely on third-party backups. All data is stored heavily encrypted and the encryption keys in each case are stored in several other data centers in different jurisdictions. This way local engineers or physical intruders cannot get access to user data."]

notes = [
  "Telegram clearly lists personal data it collects, but is also states \"To improve the security of your account, as well as to prevent spam, abuse, and other violations of our Terms of Service, we may collect metadata such as your IP address, devices and Telegram apps you've used, history of username changes, etc. If collected, this metadata can be kept for 12 months maximum.\""]

[rubric.revision-notify]
value = "yes"
citations = [
  "We will review and may update this Privacy Policy from time to time. Any changes to this Privacy Policy will become effective when we post the revised Privacy Policy on this page [Changes to this Privacy Policy](https://telegram.org/privacy#11-changes-to-this-privacy-policy). Important changes made to this Privacy Policy will be notified to you via Telegram."]
