name = "Ubuntu"
description = "Ubuntu is a GNU/Linux distribution based on Debian and composed mostly of free and open source software."
slug = "ubuntu"
hostnames = [ "ubuntu.com"]
sources = [ "https://ubuntu.com/legal/data-privacy, https://ubuntu.com/legal/systems-information-notice" ]
contributors = [ "erotavlas" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "\"You have the right to consent to our processing of personal data for marketing purposes and to ask us not to process your personal data for marketing purposes. We will usually inform you (before collecting your data) if we intend to use your data for such purposes or if we intend to disclose your information to any third party for such purposes. You can exercise your right to prevent such processing by checking certain boxes on the forms we use to collect your data.\""
]

[rubric.security]
value = "somewhat"
citations = [
  "\"We have security measures, including administrative, physical and electronic measures, to protect against the loss, exposure, misuse or alteration of information that we have collected from you in the use of the services. These measures include SSL data encryption to transmit your personal information as well as technical architectures and systems to prevent unauthorised third parties from accessing your personal information.\" \r\n\r\n \"Unfortunately, the transmission of information via the internet is not completely secure. Although we will do our best to protect your personal data, we cannot guarantee the security of your data transmitted to our site; any transmission is at your own risk. Once we have received your information, we will use strict procedures and security features to try to prevent unauthorised access.\""
]

[rubric.third-party-collection]
value = "no"
notes = [
    "Ubuntu does not collect any data from third parties."]

[rubric.history]
value = "yes"
notes = [
    "Ubuntu provides old versions of the privacy policy, but does not specify the date it was last modified. \r\n\r\n System information legal notice provides the date it was last modified."
]

[rubric.data-deletion]
value = "yes-automated"
notes = [
  ".."
]
  
[rubric.data-breaches]
value = "no"
notes = [
   "The policy does not specify a data breach protocol."]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = [
  ".."
]

[rubric.data-collection-reasoning]
value = "yes"
notes = [
  ".."
]

[rubric.noncritical-purposes]
value = "na"
citations = [
  ".."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  ".." 
]
    
[rubric.list-collected]
value = "exhaustively"
citations = [
  ".."
]

[rubric.revision-notify]
value = "yes"
citations = [
    "\"Any changes we make to our privacy policy in the future will be posted on this page and, where appropriate, notified to you by email. Please check back frequently to see any updates or changes to our privacy policy.\""
]
