name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: echo "::add-matcher::.github/problem_matcher.json"
    - run: npm test
      env:
        TEST_ENVIRONMENT: github