name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Modules
      run: npm i
    - name: Run Tests
      run: npm test
      continue-on-error: true
    - name: Publish Test Report
      uses: IgnusG/jest-report-action@v2.3.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}