name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Modules
      run: npm i
    - name: Run Tests
      run: npm test
    - name: Publish Test Report
      uses: shyim/junit-report-annotations-action@0.1.5
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}