name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Modules
      run: npm i
    - name: Run Tests
      run: npm test
    - name: Publish Test Report
      uses: ashley-taylor/junit-report-annotations-action@1.1
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}